version: '3.8'
services:
  nextjs:
    image: devrico003/next-carcenter-erding:latest
    environment:
      - AWS_REGION=eu-central-1
      - AWS_BUCKET_NAME=temp-carcenter
      - AWS_SECRET_ACCESS_KEY=MUc1izP/lGedfXswqRycqy+hLc0BG7e2kNasjmJC
      - AWS_ACCESS_KEY_ID=AKIAZ5N5WGOHU36F7M7S
      - MONGODB_URI=mongodb://mongodb:27017/
      - SENDGRID_API_KEY=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
      - ENCODED_CREDENTIALS=ZGxyX2toYWxpbGFiZHVscmFobWFuMTpadFFhQkYyV0pCYnc=
    ports:
      - "80:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
